# Generated by Django 4.1.7 on 2023-04-09 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('IDNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('firstName', models.CharField(blank=True, max_length=500, null=True)),
                ('lastName', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('placeId', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('county', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=500, null=True)),
                ('householdSize', models.CharField(blank=True, max_length=500, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('incomeLevel', models.CharField(blank=True, max_length=500, null=True)),
                ('maritalStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('educationLevel', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('fuel', models.CharField(blank=True, max_length=500, null=True)),
                ('savings', models.CharField(blank=True, max_length=500, null=True)),
                ('emissions', models.CharField(blank=True, max_length=500, null=True)),
                ('safety', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stove',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.jpg', null=True, upload_to='')),
                ('efficiency', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=40)),
                ('deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=1000, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('placeId', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.IntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('stove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.stove')),
            ],
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('status_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('message_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('network_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('message_cost', models.CharField(blank=True, max_length=1000, null=True)),
                ('credit_balance', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=1000, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=1000, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('placeId', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(blank=True, max_length=1000, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
